owner: koj-co
repo: upptime

sites:
  - name: POST to Google
    url: https://www.google.com
    method: POST

  - name: Google DNS 1
    check: "tcp-ping"
    url: 8.8.4.4
    port: 53
  - name: Google DNS 2
    check: "tcp-ping"
    url: 8.8.8.8
    port: 53
  
  
  status-website:
  baseUrl: /uptime # where "repo" is your repository name
  name: yx
